### ISSUE TITLE
Eval to cursor...

### ISSUE THREAD

**Issue by spywhere** [Naixor/eval-vscode-extension#2]
Just an idea... to eval the expression and insert it in the cursor...

For example...
![screen shot 2559-04-22 at 17 58 36](https://cloud.githubusercontent.com/assets/1087399/14739754/f097c766-08b3-11e6-8ce3-0fefe6d11b20.png)
expands to
![screen shot 2559-04-22 at 17 59 05](https://cloud.githubusercontent.com/assets/1087399/14739758/f6f5ddbe-08b3-11e6-816e-b8c40d159467.png)

**Comment by Naixor** [comment]
Ok, it sounds good, wait for next version.
