### ISSUE TITLE
Could not input any params for function after "Eval" Command 

### ISSUE THREAD

**Issue by hangxingliu** [Naixor/eval-vscode-extension#3]
I saw a action that you input some parameters what you need to execute the function after you input "Eval" command in Command Palette in the GIF images on your extension Readme page.

But I don't know why **I could not find any input area to input parameters for the function I need to execute after I input "Eval" and press "Enter"**.

**Comment by Naixor** [comment]
从id来看感觉我们能够用chinese沟通，于是...原理上我这个回去判断，如果你的函数不是自执行函数，它就会弹出输入窗，于是你的情况可能是bug或者badcase，我需要看下你的详细情况

**Comment by hangxingliu** [comment]
突然发现可以正常弹出了,~_~! 可能是Code的的问题吧.还有我觉得如果可以通过鼠标放在的一个函数名字上就可以执行的话那就更好了.谢谢
