### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Alexei-B** [Naixor/eval-vscode-extension#6]
I can't find a license mentioned in the package, source, or documentation.

**Comment by Naixor** [comment]
Em... I don't understand the specific meaning.

**Comment by Alexei-B** [comment]
Without a licence such as the MIT or ISC licences which are common for extensions, your software is copyrighted and can't be used for commercial applications. 
http://www.techrepublic.com/blog/software-engineer/the-legal-basics-of-software-licensing/

I would love to use your extension, but my company requires that you specify a licence for legal reasons.

**Comment by Naixor** [comment]
Ok. I will fix it soon.

**Comment by Naixor** [comment]
Fix it.
